apiVersion: v1
kind: Service
metadata:
  name: fincompliance-api-service
  namespace: fincompliance
  labels:
    app.kubernetes.io/name: fincompliance-rag-portal
    app.kubernetes.io/component: api
  annotations:
    cloud.google.com/neg: '{"ingress": true}'
spec:
  type: ClusterIP
  ports:
  - port: 8000
    targetPort: 8000
    protocol: TCP
    name: http
  selector:
    app.kubernetes.io/name: fincompliance-rag-portal
    app.kubernetes.io/component: api
---
apiVersion: v1
kind: Service
metadata:
  name: fincompliance-ui-service
  namespace: fincompliance
  labels:
    app.kubernetes.io/name: fincompliance-rag-portal
    app.kubernetes.io/component: ui
  annotations:
    cloud.google.com/neg: '{"ingress": true}'
spec:
  type: ClusterIP
  ports:
  - port: 8501
    targetPort: 8501
    protocol: TCP
    name: http
  selector:
    app.kubernetes.io/name: fincompliance-rag-portal
    app.kubernetes.io/component: ui
